- hosts: rancher
  become: true
  become_user: root
  tasks:
  - name: Configure SSH server
    template:
      src: sshd_config
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0644
  - name: Restart SSH
    command: systemctl restart ssh